//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ULIMSWcfClient.ULIMSGISServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wcf.ulims.com.na", ConfigurationName="ULIMSGISServiceRef.IULIMSGISService")]
    public interface IULIMSGISService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wcf.ulims.com.na/IULIMSGISService/ExecutePythonCodeMethod", ReplyAction="http://wcf.ulims.com.na/IULIMSGISService/ExecutePythonCodeMethodResponse")]
        bool ExecutePythonCodeMethod();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://wcf.ulims.com.na/IULIMSGISService/ExecutePythonCodeMethod", ReplyAction="http://wcf.ulims.com.na/IULIMSGISService/ExecutePythonCodeMethodResponse")]
        System.IAsyncResult BeginExecutePythonCodeMethod(System.AsyncCallback callback, object asyncState);
        
        bool EndExecutePythonCodeMethod(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IULIMSGISServiceChannel : ULIMSWcfClient.ULIMSGISServiceRef.IULIMSGISService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExecutePythonCodeMethodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ExecutePythonCodeMethodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ULIMSGISServiceClient : System.ServiceModel.ClientBase<ULIMSWcfClient.ULIMSGISServiceRef.IULIMSGISService>, ULIMSWcfClient.ULIMSGISServiceRef.IULIMSGISService {
        
        private BeginOperationDelegate onBeginExecutePythonCodeMethodDelegate;
        
        private EndOperationDelegate onEndExecutePythonCodeMethodDelegate;
        
        private System.Threading.SendOrPostCallback onExecutePythonCodeMethodCompletedDelegate;
        
        public ULIMSGISServiceClient() {
        }
        
        public ULIMSGISServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ULIMSGISServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ULIMSGISServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ULIMSGISServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<ExecutePythonCodeMethodCompletedEventArgs> ExecutePythonCodeMethodCompleted;
        
        public bool ExecutePythonCodeMethod() {
            return base.Channel.ExecutePythonCodeMethod();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginExecutePythonCodeMethod(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginExecutePythonCodeMethod(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndExecutePythonCodeMethod(System.IAsyncResult result) {
            return base.Channel.EndExecutePythonCodeMethod(result);
        }
        
        private System.IAsyncResult OnBeginExecutePythonCodeMethod(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginExecutePythonCodeMethod(callback, asyncState);
        }
        
        private object[] OnEndExecutePythonCodeMethod(System.IAsyncResult result) {
            bool retVal = this.EndExecutePythonCodeMethod(result);
            return new object[] {
                    retVal};
        }
        
        private void OnExecutePythonCodeMethodCompleted(object state) {
            if ((this.ExecutePythonCodeMethodCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ExecutePythonCodeMethodCompleted(this, new ExecutePythonCodeMethodCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ExecutePythonCodeMethodAsync() {
            this.ExecutePythonCodeMethodAsync(null);
        }
        
        public void ExecutePythonCodeMethodAsync(object userState) {
            if ((this.onBeginExecutePythonCodeMethodDelegate == null)) {
                this.onBeginExecutePythonCodeMethodDelegate = new BeginOperationDelegate(this.OnBeginExecutePythonCodeMethod);
            }
            if ((this.onEndExecutePythonCodeMethodDelegate == null)) {
                this.onEndExecutePythonCodeMethodDelegate = new EndOperationDelegate(this.OnEndExecutePythonCodeMethod);
            }
            if ((this.onExecutePythonCodeMethodCompletedDelegate == null)) {
                this.onExecutePythonCodeMethodCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnExecutePythonCodeMethodCompleted);
            }
            base.InvokeAsync(this.onBeginExecutePythonCodeMethodDelegate, null, this.onEndExecutePythonCodeMethodDelegate, this.onExecutePythonCodeMethodCompletedDelegate, userState);
        }
    }
}
